[phases.setup]
nixPkgs = ["zbar"]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  "/app/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/app/venv/bin/gunicorn server:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60"
