[phases.setup]
nixPkgs = ["zbar", "python312"]
aptPkgs = ["python3-pip"]

[phases.install]
cmds = ["pip3 install -r requirements.txt --break-system-packages"]

[start]
cmd = "python3 -m gunicorn server:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60"
